//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.33440
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

using UnityEngine;
using System.Collections;


public class AnimationTrigger: MonoBehaviour 
{
	public GameObject ChildAnimationObject = null;
	public string AnimationTriggerName = "";

	void Start () {

		if(ChildAnimationObject.GetComponent<Animator>() != null)
		{
			ChildAnimationObject.GetComponent<Animator>().enabled = false;
		}
	}
	
	// Update is called once per frame
	void Update () {
		
	}
	
	void OnTriggerEnter2D(Collider2D other)
	{
		if(other != null && other.gameObject != null && ChildAnimationObject != null)
		{
			TriangleShip ship = other.gameObject.GetComponent<TriangleShip>();

			Animator anima = ChildAnimationObject.GetComponent<Animator>();

			if( anima != null && ship != null) 
			{
				anima.enabled = true;

				if(AnimationTriggerName != null)
				{
					anima.SetTrigger("AnimationTriggerName");
				}
			}
		}
	}
	//

}